# Generated by Django 5.2 on 2025-01-01

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('name', models.CharField(help_text='Category name (unique per user).', max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='Optional category description.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active for the user.')),
                ('user', models.ForeignKey(help_text='Owner of this category.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('name', models.CharField(help_text='A short name for the rule (per-user unique).', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount to generate.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code, e.g., USD.', max_length=10)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Frequency of recurrence.', max_length=10)),
                ('start_date', models.DateField(help_text='Date the recurrence starts.')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date of the recurrence.', null=True)),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category to associate generated expenses with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='api.category')),
                ('user', models.ForeignKey(help_text='Owner of this recurring rule.', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount for the period.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code, e.g., USD.', max_length=10)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Budget period.', max_length=10)),
                ('start_date', models.DateField(help_text='Start date for the budget period.')),
                ('end_date', models.DateField(help_text='End date for the budget period.')),
                ('name', models.CharField(blank=True, default='', help_text="Optional label for the budget (e.g., 'Groceries Q1').", max_length=120)),
                ('category', models.ForeignKey(blank=True, help_text="Optional category for the budget. Nullable; deletion won't remove the budget.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='api.category')),
                ('user', models.ForeignKey(help_text='Owner of this budget.', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the expense.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code, e.g., USD.', max_length=10)),
                ('description', models.CharField(blank=True, default='', help_text='Optional description or memo.', max_length=255)),
                ('date', models.DateField(help_text='Date the expense occurred.')),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for the expense. Nullable; category deletions will not delete the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.category')),
                ('recurring_rule', models.ForeignKey(blank=True, help_text='Optional recurring rule that generated this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='api.recurringrule')),
                ('user', models.ForeignKey(help_text='Owner of this expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='idx_category_user_name'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['user', 'name'], name='idx_rr_user_name'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['user', 'cadence'], name='idx_rr_user_cadence'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'period', 'start_date', 'end_date'], name='idx_budget_period_window'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='idx_budget_user_category'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='idx_expense_user_date'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='idx_expense_user_category'),
        ),
    ]
